name: .NET

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Branch Names
      id: branch_name
      uses: tj-actions/branch-names@v5
      with:
        strip_tag_prefix: "v"

    - name: Set Build Environment        
      run: |
        echo "SOURCE_PR_BRANCH=${{ steps.branch_name.outputs.head_ref_branch }}" >> $GITHUB_ENV
        echo "SOURCE_BRANCH=${{ steps.branch_name.outputs.current_branch }}" >> $GITHUB_ENV
        echo "SOURCE_TAG=${{ steps.branch_name.outputs.tag }}" >> $GITHUB_ENV
        echo "CONFIGURATION=Release" >> $GITHUB_ENV        

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload NuGet package
      uses: actions/upload-artifact@v2.2.4
      with:
        # name: # optional, default is artifact
        path: "Artifacts/NuGet/*nupkg"
        if-no-files-found: warn # warn,error,ignore
        retention-days: 0 # optional
